name: Build

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          find apps/ benchmarks/ blocks/ examples/ python/ -name '*.cpp' -o -name '*.hpp' | \
          xargs -exec clang-format-18 -Werror --dry-run
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/daniestevez/gr4-packet-modem:latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc: gcc-14
            cxx: g++-14
            cmake_flags: "-DADDRESS_SANITIZER=ON"
            jobs: 1
          - cc: clang-18
            cxx: clang++-18
            cmake_flags: "-DCMAKE_LINKER=/usr/bin/clang-18"
            jobs: 4
        cmake-build-type: [ Release, Debug ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure
        if: matrix.compiler.cmake_wrapper == null
        shell: bash
        env:
          CC: "${{ matrix.compiler.cc }}"
          CXX: "${{ matrix.compiler.cxx }}"
          CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
        run: |
          source /opt/rust/env
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }} ${{ matrix.compiler.cmake_flags }} ..
      - name: Build
        shell: bash
        run: |
          source /opt/rust/env
          cd build
          make -j${{ matrix.compiler.jobs }}
      - name: Test
        shell: bash
        run: |          
          cd build
          ctest --output-on-failure
  python:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/daniestevez/gr4-packet-modem:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: CMAKE_BUILD_PARALLEL_LEVEL=4 python3 -mbuild .
      - name: Install in venv and run tests
        # --system-site-packages is needed because gr4_packet_modem
        # requires pmtv, which depends on the system numpy (as it
        # was built against it)
        run: |
          python3 -mvenv --system-site-packages env
          . env/bin/activate
          pip install numpy
          pip install dist/gr4_packet_modem*.whl
          python3 -m unittest discover -s python
  pycodestyle:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/daniestevez/gr4-packet-modem:latest
    steps:
      - uses: actions/checkout@v4
      - run: pycodestyle python
