name: Build

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          find blocks/ examples/ src/ -name '*.cpp' -o -name '*.hpp' | \
          xargs -exec clang-format -Werror --dry-run
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fair-acc/gr4-build-container:latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc: gcc-14
            cxx: g++-14
            cmake_flags: "-DADDRESS_SANITIZER=ON"
          - cc: clang-18
            cxx: clang++-18
            cmake_flags: "-DCMAKE_LINKER=/usr/bin/clang-18"
        cmake-build-type: [ Release, Debug ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure
        if: matrix.compiler.cmake_wrapper == null
        shell: bash
        env:
          CC: "${{ matrix.compiler.cc }}"
          CXX: "${{ matrix.compiler.cxx }}"
          CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }} ${{ matrix.compiler.cmake_flags }} ..
      - name: Build
        shell: bash
        run: |
          cd build
          make -j$(nproc)
      - name: Test
        shell: bash
        run: |
          cd build
          ctest --output-on-failure
